# Generated by Django 4.2.11 on 2024-04-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gamesPlayed',
            field=models.IntegerField(default=0),
        ),
    ]
