# Generated by Django 4.2.11 on 2024-05-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0005_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
