# Generated by Django 4.2.13 on 2024-06-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0008_alter_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gamesPlayed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pair',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wins',
        ),
        migrations.AddField(
            model_name='user',
            name='pongGamesPlayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pongLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pongTie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pongWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='spaceInvadersGamesPlayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='spaceInvadersLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='spaceInvadersTie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='spaceInvadersWins',
            field=models.IntegerField(default=0),
        ),
    ]
