# Generated by Django 4.2.13 on 2024-06-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0009_remove_user_gamesplayed_remove_user_losses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
