# Generated by Django 4.2.13 on 2024-06-14 09:59

from django.db import migrations, models
import transcendence.models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0010_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=transcendence.models.get_random_profile_image, upload_to='profiles/'),
        ),
    ]
