version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: transcendence_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network

  backend:
    build: ./backend
    command: >
      sh -c "python waiter.py &&
             python manage.py makemigrations --noinput transcendence &&
             python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./frontend/media:/app/transcendence/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: transcendence_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
    networks:
      - app-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/share/nginx/html/ft_transcendence
      #- ./frontend/media:/usr/share/nginx/html/ft_transcendence/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: